# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: debian-stable

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          apt install live-build cpio wget Ca-certificates apt-utils
          
          wget https://s3-us-west-1.amazonaws.com/repos.danosproject.org/2005/livebuild/danos-2005-base-Build2.4.livebuild.tar
          tar xf *livebuild.tar
          cd danos-2005-base
          
          mkdir -p config/archives/
          
          cd ./config/archives
          echo 'deb http://s3-us-west-1.amazonaws.com/repos.danosproject.org/repo/ 2005 main' > danos.list.chroot
          echo -e 'Package: *\nPin: release o=DANOS\nPin-Priority: 1000' > danos.pref.chroot
          wget https://s3-us-west-1.amazonaws.com/repos.danosproject.org/Release.key -O danos.key.chroot
          cd ../..
          
          sed -i 's/--yes/--yes --force-yes/' auto/config
          
          auto/config
          auto/build
          
          



